version: '3.8'

services:
  redis:
    image: redis/redis-stack-server:7.2.0-v10
    container_name: redis_session
    command: redis-server --requirepass ${REDIS_PASSWORD} --save "" --appendonly no
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    security_opt:
      - no-new-privileges:true
    read_only: true
    networks:
      - session_network

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  session_network:
    driver: bridge
    internal: true
