version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=30d'
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana-enterprise:10.1.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PWD}
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_PROXY_ENABLED=true
      - GF_AUTH_PROXY_HEADER_NAME=X-WEBAUTH-USER
      - GF_AUTH_PROXY_HEADER_PROPERTY=username
      - GF_AUTH_PROXY_AUTO_SIGN_UP=true
    ports:
      - "3001:3000"
    networks:
      - monitoring
    restart: unless-stopped

  redis_exporter:
    image: oliver006/redis_exporter:v1.57.0
    container_name: redis_exporter
    command:
      - '--redis.addr=redis://redis:6379'
      - '--redis.password=${REDIS_PASSWORD}'
      - '--web.listen-address=:9110'
    networks:
      - monitoring
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:v1.7.0
    container_name: node_exporter
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
      - '--collector.textfile.directory=/host/var/lib/node-exporter/'
    networks:
      - monitoring
    restart: unless-stopped

volumes:
  prom_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge
    internal: true
