scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    metrics_path: '/scrape'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis_exporter:9110

  - job_name: 'livestream_monetization'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: '/health'
