global:
  scrape_interval: 15s
  evaluation_interval: 30s
  external_labels:
    environment: production

scrape_configs:
  - job_name: 'nodejs-app'
    scheme: https
    tls_config:
      cert_file: /etc/prometheus/app.crt
      key_file: /etc/prometheus/app.key
      insecure_skip_verify: false
    basic_auth:
      username: ${PROM_USER}
      password: ${PROM_PWD}
    static_configs:
      - targets: ['app:4000']
    metrics_path: '/metrics'

  - job_name: 'redis-sessions'
    static_configs:
      - targets: ['redis_exporter:9110']
    params:
      check-keys: ['sess:*']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: redis-session-store

  - job_name: 'node-metrics'
    static_configs:
      - targets: ['node_exporter:9100']

alerting:
  alertmanagers:
    - scheme: https
      static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alerts.yml
